// src/services/pdf/reports/deanRequestHistory.js
//
// Generates the Dean Request History Report.
// Called from the Dean's Request History screen when they click
// "Download Report" after selecting a date range.
//
// Input:  object with dateFrom, dateTo, generatedBy, and requests array
// Output: jsPDF document object

import {
  createDoc,
  drawHeader,
  drawFooter,
  sectionHeading,
  guardPageBreak,
  BRAND,
  autoTable,
} from "../pdfBase";

const REPORT_TITLE = "Request History Report";

export function generateDeanRequestHistoryReport(data) {
  if (!data || !Array.isArray(data.requests)) {
    throw new Error(
      "generateDeanRequestHistoryReport: data must include a requests array."
    );
  }

  const doc = createDoc("portrait");
  let y = drawHeader(doc, REPORT_TITLE);

  y = drawMetaLine(doc, data, y);
  y = guardPageBreak(doc, y, 40, REPORT_TITLE);
  y = sectionHeading(doc, "Summary", y);
  y = drawSummarySection(doc, data.requests, y);
  y = guardPageBreak(doc, y, 40, REPORT_TITLE);
  y = sectionHeading(doc, "Request Details", y);
  drawRequestsTable(doc, data.requests, y);

  drawFooter(doc);

  return doc;
}

function drawMetaLine(doc, data, y) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const { left, right } = BRAND.margins;

  const from = data.dateFrom
    ? new Date(data.dateFrom).toLocaleDateString("en-KE", {
        day: "numeric",
        month: "long",
        year: "numeric",
      })
    : "N/A";

  const to = data.dateTo
    ? new Date(data.dateTo).toLocaleDateString("en-KE", {
        day: "numeric",
        month: "long",
        year: "numeric",
      })
    : "N/A";

  doc.setFont("helvetica", "normal");
  doc.setFontSize(BRAND.fontSize.small);
  doc.setTextColor(...BRAND.textMid);

  doc.text(`Period: ${from} — ${to}`, left, y);
  doc.text(
    `Generated by: ${data.generatedBy || "N/A"}`,
    pageWidth - right,
    y,
    { align: "right" }
  );

  doc.setDrawColor(...BRAND.textLight);
  doc.setLineWidth(0.2);
  doc.line(left, y + 2, pageWidth - right, y + 2);

  return y + 8;
}

function drawSummarySection(doc, requests, y) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const { left, right } = BRAND.margins;
  const contentWidth = pageWidth - left - right;

  // Calculate counts
  const total = requests.length;
  const approved = requests.filter((r) => r.status === "APPROVED").length;
  const declined = requests.filter((r) => r.status === "DECLINED").length;
  const pending = requests.filter((r) => r.status === "PENDING").length;

  autoTable(doc, {
    startY: y,
    margin: { left, right },
    theme: "plain",
    styles: {
      fontSize: BRAND.fontSize.tableBody,
      cellPadding: 4,
    },
    columnStyles: {
      0: { cellWidth: contentWidth / 4 },
      1: { cellWidth: contentWidth / 4 },
      2: { cellWidth: contentWidth / 4 },
      3: { cellWidth: contentWidth / 4 },
    },
    body: [
      [
        {
          content: `Total Requests\n${total}`,
          styles: {
            fontStyle: "bold",
            halign: "center",
            fillColor: BRAND.tealLight,
            textColor: BRAND.textDark,
          },
        },
        {
          content: `Approved\n${approved}`,
          styles: {
            fontStyle: "bold",
            halign: "center",
            fillColor: approved > 0 ? [220, 252, 231] : BRAND.tealLight,
            textColor: approved > 0 ? [22, 101, 52] : BRAND.textDark,
          },
        },
        {
          content: `Declined\n${declined}`,
          styles: {
            fontStyle: "bold",
            halign: "center",
            fillColor: declined > 0 ? [255, 235, 235] : BRAND.tealLight,
            textColor: declined > 0 ? BRAND.flagRed : BRAND.textDark,
          },
        },
        {
          content: `Pending\n${pending}`,
          styles: {
            fontStyle: "bold",
            halign: "center",
            fillColor: pending > 0 ? [255, 247, 230] : BRAND.tealLight,
            textColor: pending > 0 ? [180, 83, 9] : BRAND.textDark,
          },
        },
      ],
    ],
  });

  return doc.lastAutoTable.finalY + 10;
}

function drawRequestsTable(doc, requests, y) {
  const { left, right } = BRAND.margins;

  function fmtDate(iso) {
    if (!iso) return "N/A";
    return new Date(iso).toLocaleDateString("en-KE", {
      day: "numeric",
      month: "short",
      year: "numeric",
    });
  }

  const rows = requests.map((r) => ({
    cells: [
      r.requesterName || "N/A",
      r.purpose || "N/A",
      r.destination || "N/A",
      fmtDate(r.tripDate),
      r.groupSize?.toString() ?? "N/A",
      r.status || "N/A",
      fmtDate(r.approvedAt),
      r.approvalComment || "—",
    ],
    status: r.status,
  }));

  autoTable(doc, {
    startY: y,
    margin: { left, right },
    theme: "grid",

    head: [
      [
        "Requester",
        "Purpose",
        "Destination",
        "Trip Date",
        "Group",
        "Status",
        "Decision Date",
        "Comments",
      ],
    ],

    body: rows.map((r) => r.cells),

    headStyles: {
      fillColor: BRAND.teal,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: BRAND.fontSize.tableHeader,
      halign: "center",
    },

    bodyStyles: {
      fontSize: BRAND.fontSize.tableBody,
      textColor: BRAND.textDark,
    },

    columnStyles: {
      0: { cellWidth: 28 },                   // Requester
      1: { cellWidth: 30 },                   // Purpose
      2: { cellWidth: 28 },                   // Destination
      3: { cellWidth: 22, halign: "center" }, // Trip Date
      4: { cellWidth: 12, halign: "center" }, // Group
      5: { cellWidth: 18, halign: "center" }, // Status
      6: { cellWidth: 22, halign: "center" }, // Decision Date
      7: { cellWidth: "auto" },               // Comments
    },

    // Color the status cell based on value
    willDrawCell: (data) => {
      if (data.section === "body" && data.column.index === 5) {
        const row = rows[data.row.index];
        if (row.status === "APPROVED") {
          data.cell.styles.textColor = [22, 101, 52];
          data.cell.styles.fontStyle = "bold";
        } else if (row.status === "DECLINED") {
          data.cell.styles.textColor = BRAND.flagRed;
          data.cell.styles.fontStyle = "bold";
        } else if (row.status === "PENDING") {
          data.cell.styles.textColor = [180, 83, 9];
          data.cell.styles.fontStyle = "bold";
        }
      }
    },

    // When autoTable adds a new page for a long list,
    // redraw the header on that new page
    didAddPage: () => {
      drawHeader(doc, REPORT_TITLE);
    },
  });
}